apiVersion: v1
kind: ConfigMap
metadata:
  name: node-init-config
  namespace: nodeutils
data:
  install.sh: |
    #!/bin/bash

    # Setup Custom DNS
    rm -rf /etc/resolv.conf
    echo "nameserver 10.0.0.0" > /etc/resolv.conf
    chattr -f +i /etc/resolv.conf